"""Tests for streaming SHA-256 asset integrity utilities."""

from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path

from mmd_registry.hashing import (
    check_file_sha256,
    hash_file_sha256,
    is_valid_sha256,
)


class HashingTests(unittest.TestCase):
    """Tests for SHA-256 calculation and integrity comparison."""

    def setUp(self) -> None:
        self.temp_directory = tempfile.TemporaryDirectory()
        self.project_root = Path(self.temp_directory.name)

        self.payload = (
            b"MMD Asset Registry test payload.\n"
            b"This file is generated by the unit test.\n"
        )

        self.asset_file = self.project_root / "asset.bin"
        self.asset_file.write_bytes(self.payload)

        self.expected_sha256 = hashlib.sha256(self.payload).hexdigest()

    def tearDown(self) -> None:
        self.temp_directory.cleanup()

    def test_valid_sha256_format_is_accepted(self) -> None:
        self.assertTrue(is_valid_sha256(self.expected_sha256))
        self.assertTrue(is_valid_sha256(self.expected_sha256.upper()))

    def test_invalid_sha256_format_is_rejected(self) -> None:
        self.assertFalse(is_valid_sha256("not-a-sha256"))
        self.assertFalse(is_valid_sha256("a" * 63))
        self.assertFalse(is_valid_sha256("g" * 64))
        self.assertFalse(is_valid_sha256(123))

    def test_hash_file_sha256_returns_digest_and_size(self) -> None:
        actual_sha256, size_bytes = hash_file_sha256(self.asset_file)

        self.assertEqual(actual_sha256, self.expected_sha256)
        self.assertEqual(size_bytes, len(self.payload))

    def test_hash_file_sha256_supports_multiple_streaming_chunks(self) -> None:
        actual_sha256, size_bytes = hash_file_sha256(
            self.asset_file,
            chunk_size=3,
        )

        self.assertEqual(actual_sha256, self.expected_sha256)
        self.assertEqual(size_bytes, len(self.payload))

    def test_matching_expected_sha256_is_reported(self) -> None:
        result = check_file_sha256(
            self.asset_file,
            self.expected_sha256.upper(),
        )

        self.assertEqual(result.algorithm, "sha256")
        self.assertEqual(result.expected, self.expected_sha256)
        self.assertEqual(result.actual, self.expected_sha256)
        self.assertEqual(result.status, "matched")
        self.assertEqual(result.size_bytes, len(self.payload))

    def test_mismatched_expected_sha256_is_reported(self) -> None:
        result = check_file_sha256(
            self.asset_file,
            "0" * 64,
        )

        self.assertEqual(result.expected, "0" * 64)
        self.assertEqual(result.actual, self.expected_sha256)
        self.assertEqual(result.status, "mismatched")

    def test_missing_expected_sha256_is_reported(self) -> None:
        result = check_file_sha256(
            self.asset_file,
            None,
        )

        self.assertIsNone(result.expected)
        self.assertEqual(result.actual, self.expected_sha256)
        self.assertEqual(result.status, "not_recorded")

    def test_invalid_expected_sha256_is_reported(self) -> None:
        result = check_file_sha256(
            self.asset_file,
            "invalid-hash",
        )

        self.assertEqual(result.expected, "invalid-hash")
        self.assertEqual(result.actual, self.expected_sha256)
        self.assertEqual(result.status, "invalid_expected")

    def test_non_string_expected_sha256_is_reported_as_invalid(self) -> None:
        result = check_file_sha256(
            self.asset_file,
            123,
        )

        self.assertIsNone(result.expected)
        self.assertEqual(result.actual, self.expected_sha256)
        self.assertEqual(result.status, "invalid_expected")

    def test_invalid_chunk_size_is_rejected(self) -> None:
        invalid_chunk_sizes = [
            0,
            -1,
            1.5,
            True,
        ]

        for chunk_size in invalid_chunk_sizes:
            with self.subTest(chunk_size=chunk_size):
                with self.assertRaisesRegex(
                    ValueError,
                    "chunk_size must be a positive integer",
                ):
                    hash_file_sha256(
                        self.asset_file,
                        chunk_size=chunk_size,
                    )


if __name__ == "__main__":
    unittest.main()